version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 6543:5432
    volumes:
    - ./_data/db:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./_data/redis:/bitnami/redis/data
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev

    # This doesn't affect the start-up order.  But if we spin up `api`, docker-compose
    # (docker-compose up api) this indicates to the docker client that we'll 
    # need it to spin up the dependencies as well
    depends_on: 
      - postgres
      - redis
    volumes: # this supports the update-ability in our ide via volumes
       - ./api:/usr/app
    ports:
      - "3000:3000"

  